// <auto-generated />
using System;
using BackSistemaGestaoPlanosTelefonia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackSistemaGestaoPlanosTelefonia.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250221135641_nullable")]
    partial class nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackSistemaGestaoPlanosTelefonia.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BackSistemaGestaoPlanosTelefonia.Models.ClientePlano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlanoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PlanoId");

                    b.ToTable("ClientePlanos");
                });

            modelBuilder.Entity("BackSistemaGestaoPlanosTelefonia.Models.PlanoDeSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FranquiaDados")
                        .HasColumnType("int");

                    b.Property<int>("MinutosLigacao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PlanosDeSaude");
                });

            modelBuilder.Entity("BackSistemaGestaoPlanosTelefonia.Models.ClientePlano", b =>
                {
                    b.HasOne("BackSistemaGestaoPlanosTelefonia.Models.Cliente", "Cliente")
                        .WithMany("ClientePlanos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackSistemaGestaoPlanosTelefonia.Models.PlanoDeSaude", "Plano")
                        .WithMany("ClientePlanos")
                        .HasForeignKey("PlanoId");

                    b.Navigation("Cliente");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("BackSistemaGestaoPlanosTelefonia.Models.Cliente", b =>
                {
                    b.Navigation("ClientePlanos");
                });

            modelBuilder.Entity("BackSistemaGestaoPlanosTelefonia.Models.PlanoDeSaude", b =>
                {
                    b.Navigation("ClientePlanos");
                });
#pragma warning restore 612, 618
        }
    }
}
